# Generated by Django 3.2.23 on 2024-01-18 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Detaile', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Emg_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('No', models.BigIntegerField()),
                ('Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Ert_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Place', models.CharField(max_length=20)),
                ('Post', models.CharField(max_length=20)),
                ('Pin', models.IntegerField()),
                ('Email', models.CharField(max_length=20)),
                ('Phone1', models.BigIntegerField()),
                ('Phone2', models.BigIntegerField()),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Login_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
                ('Type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Place', models.CharField(max_length=20)),
                ('Post', models.CharField(max_length=20)),
                ('Pin', models.IntegerField()),
                ('Email', models.CharField(max_length=20)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcs1app.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='Request_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('Status', models.CharField(max_length=100)),
                ('Request', models.CharField(max_length=20)),
                ('ERT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcs1app.ert_table')),
                ('ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcs1app.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='Officer_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Place', models.CharField(max_length=20)),
                ('Post', models.CharField(max_length=20)),
                ('Pin', models.IntegerField()),
                ('Phone', models.BigIntegerField()),
                ('Email', models.CharField(max_length=20)),
                ('DEPARTMENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcs1app.department_table')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcs1app.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='Notification_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Notification', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('EMG_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcs1app.emg_table')),
                ('ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcs1app.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='Location_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Latitude', models.CharField(max_length=100)),
                ('Longitude', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcs1app.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feedback', models.CharField(max_length=30)),
                ('Date', models.DateField()),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcs1app.user_table')),
            ],
        ),
        migrations.AddField(
            model_name='ert_table',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcs1app.login_table'),
        ),
        migrations.AddField(
            model_name='emg_table',
            name='Officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcs1app.officer_table'),
        ),
        migrations.CreateModel(
            name='Complaint_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Complaint', models.CharField(max_length=20)),
                ('Date', models.DateField()),
                ('Latitude', models.CharField(max_length=100)),
                ('Longitude', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=100)),
                ('ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcs1app.department_table')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcs1app.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='Chat_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.CharField(max_length=30)),
                ('Date', models.DateField()),
                ('From_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ll', to='pcs1app.login_table')),
                ('To_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aa', to='pcs1app.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='Action_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Status', models.CharField(max_length=100)),
                ('COMPLAINT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcs1app.complaint_table')),
            ],
        ),
    ]
