# Generated by Django 3.2.23 on 2024-01-19 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcs1app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_table',
            name='Phone',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
