# Generated by Django 3.2.23 on 2024-01-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcs1app', '0002_user_table_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_table',
            name='Photo',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
