# Generated by Django 3.2.23 on 2024-02-10 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pcs1app', '0003_user_table_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification_table',
            name='EMG_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcs1app.ert_table'),
        ),
    ]
