# Generated by Django 3.2.23 on 2024-02-10 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcs1app', '0004_alter_notification_table_emg_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint_table',
            name='Complaint',
            field=models.FileField(upload_to=''),
        ),
    ]
