# Generated by Django 3.2.23 on 2024-02-23 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcs1app', '0005_alter_complaint_table_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_table',
            name='Latitude',
            field=models.CharField(default=-8968, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request_table',
            name='Longitude',
            field=models.CharField(default=-8968, max_length=100),
            preserve_default=False,
        ),
    ]
